// Generated by scripts/optimize-images.mjs. Do not edit by hand; re-run the script instead.
// Each entry lists the widths available as /images/site/<name>-<width>.webp and .jpg.
export interface SiteImageInfo {
  width: number;
  height: number;
  widths: number[];
}

export const SITE_IMAGES = {
  'hero-home': { width: 2400, height: 1350, widths: [640, 1024, 1600, 2400] },
  'hero-home-mobile': { width: 1290, height: 2293, widths: [640, 1024, 1290] },
  'track-hero': { width: 2400, height: 1200, widths: [640, 1024, 1600, 2400] },
  'locations-hero': { width: 2400, height: 1200, widths: [640, 1024, 1600, 2400] },
  'callback-banner': { width: 2400, height: 800, widths: [640, 1024, 1600, 2400] },
  'services-hero': { width: 2400, height: 1000, widths: [640, 1024, 1600, 2400] },
  'about-hero': { width: 2400, height: 1000, widths: [640, 1024, 1600, 2400] },
  'about-compliance': { width: 2400, height: 800, widths: [640, 1024, 1600, 2400] },
  'ship-hero': { width: 2400, height: 1350, widths: [640, 1024, 1600, 2400] },
  'quote-result-hero': { width: 2400, height: 1350, widths: [640, 1024, 1600, 2400] },
  'service-priority-express': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'service-freight-linehaul': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'service-vehicle-transport': { width: 340, height: 340, widths: [340] },
  'service-secure-vault': { width: 340, height: 340, widths: [340, 640] },
  'industry-healthcare': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'industry-technology': { width: 340, height: 340, widths: [340, 640] },
  'industry-automotive': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'industry-ecommerce': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'track-result-vehicle': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'about-operations': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'about-story': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'contact-team': { width: 340, height: 340, widths: [340, 640, 1024, 1400] },
  'about-team': { width: 340, height: 340, widths: [340, 640] },
} satisfies Record<string, SiteImageInfo>;

export type SiteImageName = keyof typeof SITE_IMAGES;
